routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/registrame', 'ClienteController@admin');

Route::prefix('/clientes')->name('clientes.')->group(function () {
    Route::get('/', 'ClienteController@index')->name('index');
    Route::get('/get', 'ClienteController@clientes')->name('get');
    Route::post('/store', 'ClienteController@store')->name('store');
    Route::delete('/{id}/delete', 'ClienteController@destroy')->name('delete');
});

Route::prefix('/equipamiento')->name('equipos.')->group(function () {
    Route::get('/', 'EquipamientoController@index')->name('index');
    Route::get('/get', 'EquipamientoController@equipos')->name('get');
    Route::put('/{id}/update', 'EquipamientoController@update')->name('update');
    Route::post('/store', 'EquipamientoController@store')->name('store');
    Route::delete('/{id}/delete', 'EquipamientoController@destroy')->name('delete');
});

Route::prefix('/planes')->name('planes.')->group(function () {
    Route::get('/', 'PlanController@index')->name('index');
    Route::get('/get', 'PlanController@planes')->name('get');
    Route::post('/store', 'PlanController@store')->name('store');
    Route::delete('/{id}/delete', 'PlanController@destroy')->name('delete');
});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/partials/footer.blade.php
<div class="content">
    <p class="has-text-blue has-text-weight-bold is-size-7">
        Desarrollado por Fernando Liévano
    </p>
    <p>
        <a href="https://bulma.io">
            <img src="{{ asset('img/made-with-bulma--white.png') }}" class="bulma-img" alt="made with Bulma">
        </a>
    </p>
</div>

resources/views/partials/navbar.blade.php
 <nav class="navbar is-dark" role="navigation" aria-label="navigation">
     <div class="navbar-brand">
         <a class="navbar-item" href="/home">
             <i class="fas fa-home"></i>
         </a>
         <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
             <span aria-hidden="true"></span>
             <span aria-hidden="true"></span>
             <span aria-hidden="true"></span>
         </a>
     </div>
     <div id="navbar" class="navbar-menu">
         <div class="navbar-start">
             <a href="{{ route('clientes.index') }}" class="navbar-item">
                 <span class="icon has-text-link">
                     <i class="fas fa-users"></i>
                 </span>
                 <span>Clientes</span>
             </a>
             <a href="{{ route('planes.index') }}" class="navbar-item">
                 <span class="icon has-text-info">
                     <i class="fas fa-wifi"></i>
                 </span>
                 <span>
                     Planes
                 </span>
             </a>
             <a href="{{ route('equipos.index') }}" class="navbar-item">
                 <span class="icon has-text-primary">
                       <i class="fas fa-hdd"></i>
                 </span>
                 <span>Equipamiento</span>
             </a>
             <a href="#" class="navbar-item">
                 <span class="icon has-text-success">
                     <i class="fas fa-money-check-alt"></i>
                 </span>
                 <span>Tickets</span>
             </a>
         </div>
         <div class="navbar-end">
             @if (Auth::check())
                <div class="navbar-item has-dropdown is-hoverable">
                    <div class="navbar-link">
                        Opciones
                    </div>
                    <div class="navbar-dropdown is-right">
                            <a class="navbar-item" href="#">
                                <span class="icon is-small">
                                    <i class="fas fa-cog"></i>
                                </span>
                                <span>Ajustes</span>
                            </a>
                            <a href="{{ route('logout') }}" class="navbar-item"
                                onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit();">
                                <span class="icon is-small">
                                    <i class="fas fa-sign-out-alt"></i>
                                </span>
                                <span>
                                    Cerrar sesión
                                </span>
                            </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </div>
             @endif
         </div>
     </div>
 </nav>